[package]
name = "raylar-audio-recorder-service"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "raylar_audio_recorder_service"
path = "src/lib.rs"

[features]
default = []
defmt = [
    "dep:defmt",
    "raylar-audiosource/defmt",
    "raylar-storage-service/defmt",
    "raylar-time-service/defmt",
]

[dependencies]
defmt = { workspace = true, optional = true }
heapless = "0.8.0"
raylar-audiosource = { path = "../../metadrivers/audiosource" }
raylar-storage-service = { path = "../storage" }
raylar-time-service = { path = "../time", default-features = false }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
defmt = { workspace = true, features = ["unstable-test"] }
embassy-time = { workspace = true, features = ["std"] }
embassy-executor = { version = "0.10.0", features = ["executor-thread", "platform-std"] }
